### ISSUE TITLE
Support for R9M70

### ISSUE THREAD

**Issue by Marcussjogren** [pklokke/SmartThings-WiserSmartDevices#1]
Hi!

Do you believe it would be possible to adds upport for this energy meter or is it just heating devices that is supported by your plugin?

https://www.se.com/ww/en/product/R9M70/energy-sensor%2C-powertag-resi9-flex-63a-3p%2Bn-top-and-bottom-position/

**Comment by pklokke** [comment]
Sorry, I don't have these devices, nor access to any documentation to help integrate them.

A bit of quick reading shows that these are greenpower devices:
https://zigbeealliance.org/zigbee_products/powertag-3pn-400v-flex/

and unfortunately smartthings has been dragging their feet on supporting greenpower sink for some time now:
https://community.smartthings.com/t/zigbee-3-0-green-power-support/62602/12

So it might be a deadend I'm afraid.
