### ISSUE TITLE
joining procedure 

### ISSUE THREAD

**Issue by NeOdYmS** [pklokke/SmartThings-WiserSmartDevices#2]
Hello

iam trying to join a eer51000 with a cc2531 flashed with zigbee2mqtt 1.21 default firmware 
But do not see anything in zigbee2mqtt front end

**Comment by pklokke** [comment]
Hi, this repo is more for the work I did on SmartThings, before I moved over to using zigbee2mqtt.

Its important when joining to hold the set button for five seconds, although it looks the same after releasing as a short press, it will not join a standard zigbee network like SmartThings or Z2M.

Can you check what version of software is on the RTS (EER51000).  If its a very old version, it may not support the standard HA Join.

**Comment by pklokke** [comment]
To check the version, pull the batteries out, press a few buttons to drain it, and then pop the batteries in, on its splash screen it will briefly show the version of the application it is running.

**Comment by NeOdYmS** [comment]
thank you for yours quick answer and sorry to ask it here

this is the rts version number :

![D18FD99C-03B8-44FC-B9D3-A717ABC5B9BC](https://user-images.githubusercontent.com/54035566/131228679-ff8804bb-d268-4d57-b8b1-a121bbe50475.jpeg)

**Comment by NeOdYmS** [comment]
Ok i find the way !
I don't have to wait the orange state to push 5 sec the set bouton!

**Comment by pklokke** [comment]
Yes! I should be more clear on that.  You need to get the LED (light diode) back to orange, then press and hold set for five seconds, then release.  It doesn't look different, but underneath it changes the join parameters to accept non-wiser gateways.

Happy you got it resolved. 👍
